name: snakerobots-prod-worker

services:
  tunnel:
    image: alpine:latest
    command: >
      sh -c "apk add --no-cache openssh-client autossh &&
      autossh -M 0 -N
      -o ServerAliveInterval=60
      -o ServerAliveCountMax=3
      -L 0.0.0.0:5432:0.0.0.0:5432
      $SSH_DEST"
    volumes:
      - ./ssh:/root/.ssh
    env_file:
      - .env
    restart: unless-stopped
  worker:
    build:
      context: ../..
      dockerfile: worker.Dockerfile
    restart: always
    depends_on:
      - tunnel
    environment:
      WORKER_INTERVAL: 15
      WORKER_MAX_GAMES: 1
    env_file:
      - .env
