version: "3.8"

services:
  vitepress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    volumes:
      - /srv/download:/usr/share/nginx/html/download
    restart: unless-stopped
