real_ip_header CF-Connecting-IP;

set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;

limit_req_zone $binary_remote_addr zone=global_rate_limit:10m rate=20r/s;
limit_req_zone $binary_remote_addr zone=auth_rate_limit:10m rate=1r/s;

limit_req_status 429;

server {
    listen 3000;
    server_name _;

    location /auth/ {
        limit_req zone=auth_rate_limit burst=2 nodelay;

        proxy_pass http://app:3000;
        proxy_set_header Host $host;
    }

    location / {
        limit_req zone=global_rate_limit burst=40 nodelay;

        proxy_pass http://app:3000;
        proxy_set_header Host $host;
    }
}